### ISSUE TITLE
解析失败

### ISSUE THREAD

**Issue by Jonnyan404** [richshaw2015/dino-rss-electron#28]
podcast rss地址: <https://anchor.fm/s/70807210/podcast/rss>

**Comment by richshaw2015** [comment]
服务器所在的区域被限制访问了😭😭
`<html><body>Anchor на данный момент недоступен в России. Мы надеемся, <a href="https://help.anchor.fm/hc/en-us/articles/5181704556187-Services-Suspended-in-Russia-on-April-11th-2022">эта информация</a> поможет ответить на ваши вопросы.</body></html>`

**Comment by Jonnyan404** [comment]
[rss.txt](https://github.com/richshaw2015/dino-rss-electron/files/10712574/rss.txt)

我下载下来了,你看一下是否可用,如果还需要其它信息,我再提供.

**Comment by richshaw2015** [comment]
修复了

**Comment by Jonnyan404** [comment]
我试了一下,还有报错,如图所示:
![image](https://user-images.githubusercontent.com/20352705/219390932-3138468d-7e00-4aed-9c80-4933978e983e.png)

**Comment by richshaw2015** [comment]
我这看是好的，已经在服务器修复了。应该是你地址没有输入正确，试试完整 URL：
`https://anchor.fm/s/70807210/podcast/rss`

**Comment by Jonnyan404** [comment]
![image](https://user-images.githubusercontent.com/20352705/219395756-2fafa7c2-c68e-413d-a59b-30001d88fd7a.png)

我复制粘贴的,地址是完整的.

**Comment by Jonnyan404** [comment]
> https://anchor.fm/s/70807210/podcast/rss

好了,有点奇怪,我复制你发的地址就好了
